version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]
    assignees:
      - "mkpro118"
    labels:
      - "type: upkeep"
      - "domain: Rust"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "mkpro118"
    labels:
      - "type: upkeep"
      - "domain: GitHub Actions"
